### ISSUE TITLE
python3

### ISSUE THREAD

**Issue by zvezdochiot** [ImageProcessing-ElectronicPublications/python-cropper-tk#1]
Hi @notha99y . Could you check the current state for compatibility with python3?

https://github.com/ImageProcessing-ElectronicPublications/python-cropper-tk/blob/883af2661772827308aa3b59e745f1a5afe57c1f/croppertk.py#L17-L35

**Comment by notha99y** [comment]
Does not seem to work for me.

Have the following error.
> Traceback (most recent call last):
  File "test.py", line 18, in <module>
    import Image
ModuleNotFoundError: No module named 'Image'

>

**Comment by notha99y** [comment]
`import os
import sys

py_version = sys.version

if py_version[0] == "2":
    # for Python2
    import Image
    import ImageFilter
    import ImageTk
    import Tkinter as tk
    import tkFileDialog as tkfd

elif py_version[0] == "3":
    # for Python3
    from PIL import Image, ImageTk, ImageFilter
    import tkinter as tk
    from tkinter import filedialog as tkfd

else:
    pass

PROGNAME = "Cropper-Tk"
VERSION = "0.20200419"

thumbsize = 896, 608
thumboffset = 16`

**Comment by notha99y** [comment]
'''python
import os
import sys

py_version = sys.version

if py_version[0] == "2":
    # for Python2
    import Image
    import ImageFilter
    import ImageTk
    import Tkinter as tk
    import tkFileDialog as tkfd

elif py_version[0] == "3":
    # for Python3
    from PIL import Image, ImageTk, ImageFilter
    import tkinter as tk
    from tkinter import filedialog as tkfd

else:
    pass

PROGNAME = "Cropper-Tk"
VERSION = "0.20200419"

thumbsize = 896, 608
thumboffset = 16
'''

**Comment by notha99y** [comment]
Do check out my pull request

**Comment by zvezdochiot** [comment]
Hi @notha99y .

Again I need to check the compatibility of the current state. Waiting for feedback.
