### ISSUE TITLE
Enhancement Ideas for Wallpaper Cropping

### ISSUE THREAD

**Issue by UndarkAido** [ImageProcessing-ElectronicPublications/python-cropper-tk#4]
I was looking for a program very similar to this to process wallpapers and I was wondering if two point would even be possible: a minimum resolution and a fixed ratio (I could downsize everything to the proper resolution afterwards but that would also be cool)

**Comment by zvezdochiot** [comment]
@UndarkAido say:
>a minimum resolution and a fixed ratio

Do you want to added resize? Not. It doesn't belong here. This tool is about something else.

**Comment by UndarkAido** [comment]
Resize would be cool but I'm fine without that. The main things are that I want all the crops to have the same ratio and not be smaller than a certain size.

**Comment by zvezdochiot** [comment]
@UndarkAido say:
>The main things are that I want all the crops to have the same ratio and not be smaller than a certain size.

Lay out graphic samples and expected result.

PS: But I'm sure that your wishes have nothing to do with this tool.

**Comment by UndarkAido** [comment]
I'm trying to run it but this happens:
```
 > python .\croppertk.py3 .\BotW-Climbing.jpg
Traceback (most recent call last):
  File ".\croppertk.py3", line 405, in <module>
    main()
  File ".\croppertk.py3", line 399, in main
    app = Cropper(filename=filename)
TypeError: __init__() got an unexpected keyword argument 'filename'
```
Edit: I'm running Python 3.8.3

**Comment by zvezdochiot** [comment]
@UndarkAido say:
>`.\croppertk.py3`  
>`.\BotW-Climbing.jpg`

`.\`???

**Comment by UndarkAido** [comment]
I'm on Windows

**Comment by UndarkAido** [comment]
I did this:
```python
    def __init__(self, filename, master=None):
        self.filename = filename
```

I guess I suppose `filename` isn't the name of the file you open- should've read more thoroughly.

Now I get this when I open a file:

```
Traceback (most recent call last):
  File "./croppertk.py3", line 407, in <module>
    main()
  File "./croppertk.py3", line 402, in main
    app.master.title(PROGNAME)
AttributeError: 'NoneType' object has no attribute 'title'
```

**Comment by zvezdochiot** [comment]
@UndarkAido say:
>I'm on Windows

Especially. Type:
```sh
python croppertk.py3 BotW-Climbing.jpg
```

**Comment by UndarkAido** [comment]
Huh, ok. Still getting the same error though.

**Comment by zvezdochiot** [comment]
@UndarkAido say:
>Still getting the same error though.

What does say ?: 
```sh
python croppertk.py BotW-Climbing.jpg
```
Use copy-paste.

**Comment by UndarkAido** [comment]
Oh wait I'd changed it to `test.jpg` but when the file is there:
```
> python croppertk.py BotW-Climbing.jpg
Traceback (most recent call last):
  File "croppertk.py", line 24, in <module>
    reload(sys)
NameError: name 'reload' is not defined
```

**Comment by UndarkAido** [comment]
Here I made a mockup in paint. I want to crop out multiple images like this was made to do I just want them to all be the same ratio: ![Mockup](https://user-images.githubusercontent.com/7421794/107694034-7fbc8700-6c74-11eb-9776-da7c3f2e2e12.png)

**Comment by zvezdochiot** [comment]
@UndarkAido say:
>NameError: name 'reload' is not defined

Added before:
```python
from importlib import reload
```
and repeat.

**Comment by UndarkAido** [comment]
Oh I just realized that was `.py` instead of `.py3`
```
> python croppertk.py BotW-Climbing.jpg
Traceback (most recent call last):
  File "croppertk.py", line 27, in <module>
    sys.setdefaultencoding(sys.stdout.encoding)
AttributeError: module 'sys' has no attribute 'setdefaultencoding'
```

**Comment by zvezdochiot** [comment]
@UndarkAido say:
>

https://github.com/ImageProcessing-ElectronicPublications/python-cropper-tk/blob/afae4e32abdebc0799faa711dcd00471b2646e9c/croppertk.py#L24-L25
to:
```python
'''
reload(sys)
sys.setdefaultencoding(sys.stdout.encoding)
'''
```
and repeat.

**Comment by UndarkAido** [comment]
I commented out the line for setting the window name in `.py3` and I get this when I click 'Crops' 
```
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Python38\lib\tkinter\__init__.py", line 1883, in __call__
    return self.func(*args)
  File "croppertk.py3", line 239, in start_cropping
    newdir = Path.mkdir(Path.cwd() / ('crops_' + self.filename))
  File "C:\Python38\lib\pathlib.py", line 1284, in mkdir
    self._accessor.mkdir(self, mode)
OSError: [WinError 123] The filename, directory name, or volume label syntax is incorrect: 'C:\\Users\\aedwards\\Downloads\\python-cropper-tk-master\\crops_C:\\Users\\aedwards\\Downloads\\Flickr Walls\\Wallpapers - Breath of the Wild\\gtUWQHD\\BotW-Render01.jpg'
```

**Comment by UndarkAido** [comment]
> @UndarkAido say:
> 
> > 
> 
> https://github.com/ImageProcessing-ElectronicPublications/python-cropper-tk/blob/afae4e32abdebc0799faa711dcd00471b2646e9c/croppertk.py#L24-L25
> 
> 
> to:
> ```python
> '''
> reload(sys)
> sys.setdefaultencoding(sys.stdout.encoding)
> '''
> ```
> 
> and repeat.

It works!

**Comment by UndarkAido** [comment]
But yeah so I want to be able to do this but with a fixed ratio and minimum size: 
![image](https://user-images.githubusercontent.com/7421794/107696405-88fb2300-6c77-11eb-950f-c65218614ff5.png)

**Comment by zvezdochiot** [comment]
@UndarkAido say:
>But yeah so I want to be able to do this but with a fixed ratio and minimum size:

This is UB.

**Comment by UndarkAido** [comment]
> @UndarkAido say:
> 
> > But yeah so I want to be able to do this but with a fixed ratio and minimum size:
> 
> This is UB.

I'm not familiar with what 'UB' means?

**Comment by zvezdochiot** [comment]
@UndarkAido say:
>I'm not familiar with what 'UB' means?

Undefined behavior.

**Comment by UndarkAido** [comment]
Oh, I don't think that's what undefined behavior means?
> In computer programming, undefined behavior is the result of executing a program whose behavior is prescribed to be unpredictable, in the language specification to which the computer code adheres.

It's a feature request? I don't understand how that's undefined behavior.

Edit: If you think it's out of scope for the project that's fine, just thought it couldn't hurt to ask.

**Comment by zvezdochiot** [comment]
@UndarkAido say:
>I don't understand how that's undefined behavior.

UB is in your wishes. I will not implement it.

**Comment by zvezdochiot** [comment]
Hi @UndarkAido .

See https://github.com/ImageProcessing-ElectronicPublications/python-cropper-tk/releases/tag/0.20210218

**Comment by abubelinha** [comment]
> I'm on Windows

As for @UndarkAido [comment](https://github.com/ImageProcessing-ElectronicPublications/python-cropper-tk/issues/4#issuecomment-777759585) it seems this tool is Windows compatible. 
Can you provide some guide on how to install it?
All apt-get commands I see in README look like Linux installation steps.

Thanks
@abubelinha

**Comment by zvezdochiot** [comment]
@abubelinha say:
>Can you provide some guide on how to install it?

No. I do not communicate with Windows.

**Comment by abubelinha** [comment]
Thanks @zvezdochiot but I was asking @UndarkAido

**Comment by UndarkAido** [comment]
> > I'm on Windows
> 
> As for @UndarkAido [comment](https://github.com/ImageProcessing-ElectronicPublications/python-cropper-tk/issues/4#issuecomment-777759585) it seems this tool is Windows compatible. 
> Can you provide some guide on how to install it?
> All apt-get commands I see in README look like Linux installation steps.
> 
> Thanks
> @abubelinha
> 
>  

I never got it to run, I wrote [WallpaperGarden](https://github.com/UndarkAido/WallpaperGarden) for my purposes instead

Edit: Oh we did get it to run, you just have to scroll up
